version: '3'
services:

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: experiment

    ports:
      - "5432:5432"

  prometheus:
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"