server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application.name: base

  datasource:
    url: jdbc:postgresql://localhost:5432/experiment
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

    defer-datasource-initialization: true